mobile = "mobile"
v1_path = f"/{mobile}/api/v1"
v4_path = f"/{mobile}/api/v4"
token_request_path = f"{v1_path}/oauth/request_token"
auth_request_path = f"{v1_path}/oauth/token"
privileges_request_path = f"{v4_path}/profile/privileges"
